### ISSUE TITLE
unable to clone

### ISSUE THREAD

**Issue by wzis** [artyom-tarasenko/qemu#6]
# git clone https://github.com/artyom-tarasenko/qemu.git
Initialized empty Git repository in /emu/qemu/qemu/.git/
error:  while accessing https://github.com/artyom-tarasenko/qemu.git/info/refs

fatal: HTTP request failed

**Comment by vladmovchan** [comment]
`git clone` command from above works fine for me from multiple locations.
It is probably something on your side (like lack of CA certificates installed in the system or some proxy in the middle).
Try to clone any other repo from `github` via `https`, check if you can access anything via `https` from the console. If any of this two operations fail than it is definitely something on your side.
As the fallback you could try to use `http` instead of `https` or clone the repository via `ssh`.

**Comment by wzis** [comment]
http also got same problem:
# git clone http://github.com/artyom-tarasenko/qemu/tree/40p-20190406-aix-boots
Initialized empty Git repository in /emu/qemu/40p-20190406-aix-boots/.git/
error:  while accessing http://github.com/artyom-tarasenko/qemu/tree/40p-20190406-aix-boots/info/refs

fatal: HTTP request failed


# git clone http://github.com/artyom-tarasenko/qemu.git
Initialized empty Git repository in /emu/qemu/qemu/.git/
error:  while accessing http://github.com/artyom-tarasenko/qemu.git/info/refs

fatal: HTTP request failed

**Comment by alexshukin** [comment]
Clicking any of the links:
http://github.com/artyom-tarasenko/qemu.git/info/refs
or 
https://github.com/artyom-tarasenko/qemu.git/info/refs
I can see the following:
Please upgrade your git client.
GitHub.com no longer supports git over dumb-http: https://github.com/blog/809-git-dumb-http-transport-to-be-turned-off-in-90-days

**Comment by wzis** [comment]
Not sure why, the git on CentOS6.6 and Ubuntu11.04 both have problem to get the qemu from your site, but now I have got it on a Oracle Linux 7.5.
So it seems the git version on CentOS and Ubuntu older versions of Linux does not compatible with the server.
Thanks anyway, for your effort to help me.

Best Regards,

Roger

**Comment by artyom-tarasenko** [comment]
Yes, the old good unsecure http is getting extinct nowadays. This is not the inssue of this repository but the GitHub itself though
